### ISSUE TITLE
Argo Links causes "Invalid post type" error when bulk editing posts

### ISSUE THREAD

**Issue by rnagle** [INN/argo-links#5]
Steps to reproduce:

1. Filter posts by category.
2. Select all posts.
3. Choose "Bulk edit."
4. Choose a category to assign to selected posts and click "Update."

I haven't tracked down exactly what's going wrong, but I spotted a "post_type=Array" in the GET parameters of the URL that shows after attempting to update the posts. Finding out why that's happening is probably a good place to start.

**Comment by benlk** [comment]
Was able to reproduce this. 

1. In Link Roundups > Link Roundups, filter by category. 
2. Select all/multiple posts.
3. Choose "Bulk Edit"
4. Assign a category that at least one story is not in
5. Click Update. 

Here's the url, broken up by parameters:

    http://vagrant.dev/wp-admin/edit.php
    ?s=
    &post_status=all
    &post_type=Array
    &_wpnonce=eec96706f4
    &_wp_http_referer=%2Fwp-admin%2Fedit.php%3Fs%26post_status%3Dall%26post_type%3Dargolinkroundups%26action%3D-1%26m%3D0%26cat%3D70%26filter_action%3DFilter%26paged%3D1%26mode%3Dlist%26action2%3D-1
    &action=edit
    &m=0
    &cat=70
    &paged=1
    &mode=list
    &post_category%5B%5D=0
    &post_category%5B%5D=69
    &post_category%5B%5D=70
    &tax_input%5Bpost_tag%5D=
    &post_author=-1
    &comment_status=
    &ping_status=
    &_status=-1
    &bulk_edit=Update
    &post_view=list
    &screen=edit-argolinkroundups
    &post%5B%5D=2409
    &post%5B%5D=2394
    &action2=-1

It does look like post_type is wrong.

    <input type="hidden" name="post_type" class="post_type_page" value="Array">

Changing `Array` to `argolinkroundups` before submitting does allow the request to go through.

The value is set in wp-admin/edit.php:

    <input type="hidden" name="post_type" class="post_type_page" value="<?php echo $post_type; ?>" />

$post_type is set [earlier in that file](https://github.com/WordPress/WordPress/blob/master/wp-admin/edit.php#L21-L23):

    global $post_type, $post_type_object;
    $post_type = $typenow; 

$typenow isn't set in this file, but it is set in `require_once( dirname( __FILE__ ) . '/admin.php'`, 

    if ( isset( $_REQUEST['post_type'] ) && post_type_exists( $_REQUEST['post_type'] ) )
        $typenow = $_REQUEST['post_type'];
    else
        $typenow = '';

But it's set to argolinkroundups on this page when the page reloads, so it should be good. 

Instead, it's `array (  0 => 'argolinkroundups',  1 => 'argolinkroundups', )`. 

I'm fairly sure that's because of [line 2715 of wp-includes/query.php](https://github.com/WordPress/WordPress/blob/master/wp-includes/query.php#L2715).

More digging there in the next comment.

**Comment by benlk** [comment]
https://github.com/INN/argo-links/commit/68f9a95bfb763c17af4ca41c69178ce28fb2408c is a fix, preventing the filter from duplicating the argolinks slug in the post type array.
